"""Automated comparison runner — Adaptive vs Fixed-Time delta reports."""

import json
import logging
import os
from datetime import datetime

log = logging.getLogger("flowsense.simulation")

SUMMARY_DIR = os.path.join("output", "summary")


def find_latest_report(mode_slug: str) -> str | None:
    """Find the most recent JSON report file matching a given mode slug."""
    if not os.path.isdir(SUMMARY_DIR):
        return None

    candidates = [
        f for f in os.listdir(SUMMARY_DIR)
        if f.startswith(f"report_{mode_slug}") and f.endswith(".json")
    ]
    if not candidates:
        return None

    candidates.sort(reverse=True)
    return os.path.join(SUMMARY_DIR, candidates[0])


def compute_comparison_deltas(adaptive_data: dict, fixed_data: dict) -> dict:
    """Compute percentage deltas between adaptive and fixed-time simulation results.

    Returns a dict with metric name -> {adaptive, fixed, delta, pct_change, improved}.
    """
    ag = adaptive_data.get("global", {})
    fg = fixed_data.get("global", {})

    metrics_to_compare = [
        ("avg_travel_time_s",     "Avg Travel Time (s)",     "lower_better"),
        ("avg_waiting_time_s",    "Avg Waiting Time (s)",    "lower_better"),
        ("avg_time_loss_s",       "Avg Time Loss (s)",       "lower_better"),
        ("avg_stops_per_vehicle", "Avg Stops / Vehicle",     "lower_better"),
        ("avg_depart_delay_s",    "Avg Departure Delay (s)", "lower_better"),
        ("total_vehicles",        "Total Vehicles Served",   "higher_better"),
        ("pct_vehicles_stopped",  "% Vehicles Stopped",      "lower_better"),
        ("total_fuel_L",          "Total Fuel (L)",          "lower_better"),
        ("total_CO2_kg",          "Total CO2 (kg)",          "lower_better"),
    ]

    results = {}
    for key, label, direction in metrics_to_compare:
        a_val = ag.get(key, 0)
        f_val = fg.get(key, 0)
        delta = a_val - f_val

        if f_val != 0:
            pct = round((delta / abs(f_val)) * 100, 2)
        else:
            pct = 0.0

        if direction == "lower_better":
            improved = delta < 0
        else:
            improved = delta > 0

        results[key] = {
            "label": label,
            "adaptive": a_val,
            "fixed": f_val,
            "delta": round(delta, 2),
            "pct_change": pct,
            "improved": improved,
        }

    return results


def write_comparison_report(adaptive_data: dict, fixed_data: dict, deltas: dict):
    """Write a comparison Markdown and JSON report to the summary directory."""
    os.makedirs(SUMMARY_DIR, exist_ok=True)
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")

    comparison_data = {
        "timestamp": datetime.now().isoformat(timespec="seconds"),
        "adaptive": adaptive_data.get("global", {}),
        "fixed_time": fixed_data.get("global", {}),
        "deltas": deltas,
    }
    json_path = os.path.join(SUMMARY_DIR, f"comparison_{timestamp}.json")
    with open(json_path, "w", encoding="utf-8") as f:
        json.dump(comparison_data, f, indent=2, ensure_ascii=False)

    lines = [
        "# Adaptive vs Fixed-Time — Comparison Report",
        "",
        f"**Generated**: `{comparison_data['timestamp']}`",
        "",
        "| Metric | Adaptive | Fixed-Time | Delta | % Change | Result |",
        "|:-------|--------:|-----------:|------:|---------:|:------:|",
    ]
    for key, info in deltas.items():
        result = "Better" if info["improved"] else ("Same" if info["delta"] == 0 else "Worse")
        a_str = f"{info['adaptive']:.2f}" if isinstance(info['adaptive'], float) else str(info['adaptive'])
        f_str = f"{info['fixed']:.2f}" if isinstance(info['fixed'], float) else str(info['fixed'])
        lines.append(
            f"| {info['label']} | {a_str} | {f_str} | {info['delta']:+.2f} | {info['pct_change']:+.1f}% | {result} |"
        )

    lines += ["", "---", "", "*Auto-generated by FlowSense SUMO Simulation.*"]

    md_path = os.path.join(SUMMARY_DIR, f"comparison_{timestamp}.md")
    with open(md_path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))

    log.info("Comparison report saved: %s, %s", md_path, json_path)


def run_comparison_analysis():
    """Load latest Adaptive and Fixed-Time reports, compute deltas, and write comparison."""
    adaptive_path = find_latest_report("adaptive_control")
    fixed_path = find_latest_report("fixed_time_program")

    if not adaptive_path:
        log.error("No Adaptive-Control report found. Run adaptive simulation first.")
        return
    if not fixed_path:
        log.error("No Fixed-Time-Program report found. Run fixed-time simulation first.")
        return

    with open(adaptive_path, "r", encoding="utf-8") as f:
        adaptive_data = json.load(f)
    with open(fixed_path, "r", encoding="utf-8") as f:
        fixed_data = json.load(f)

    log.info("Computing Adaptive vs Fixed-Time performance deltas...")

    deltas = compute_comparison_deltas(adaptive_data, fixed_data)

    for key, info in deltas.items():
        status = "BETTER" if info["improved"] else ("SAME" if info["delta"] == 0 else "WORSE")
        log.info("  %s: adaptive=%.2f, fixed=%.2f, delta=%+.2f (%+.1f%%) [%s]",
                 info["label"], info["adaptive"] if isinstance(info["adaptive"], float) else info["adaptive"],
                 info["fixed"] if isinstance(info["fixed"], float) else info["fixed"],
                 info["delta"], info["pct_change"], status)

    write_comparison_report(adaptive_data, fixed_data, deltas)
